name       : python-oauthlib
version    : 3.2.1
release    : 10
source     :
    - https://github.com/oauthlib/oauthlib/archive/refs/tags/v3.2.1.tar.gz : ca2c86689bc6687d96914162af02858016c3bcf478c860bf9f52ab694848c435
homepage   : https://github.com/oauthlib/oauthlib
license    : BSD-3-Clause
component  : programming.python
summary    : A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
description: |
    OAuthLib is a generic utility which implements the logic of OAuth without assuming a specific HTTP request object or web framework. Use it to graft OAuth client support onto your favorite HTTP library, or provide support onto your favourite web framework. If you're a maintainer of such a library, write a thin veneer on top of OAuthLib and get OAuth support for very little effort.
builddeps  :
    - python-blinker    # check
    - python-mock       # check
    - python-nose       # check
    - python-pyjwt      # check
rundeps    :
    - python-cryptography
setup      : |
    # python-unittest2 is now provided by "python" package and python-unittest is retired
    sed -i "s/'unittest2', //" setup.py
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
