name       : python-oauthlib
version    : 2.1.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/o/oauthlib/oauthlib-2.1.0.tar.gz : ac35665a61c1685c56336bda97d5eefa246f1202618a1d6f34fccb1bdd404162
license    : BSD-3-Clause
component  : programming.python
summary    : A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
description: |
    OAuthLib is a generic utility which implements the logic of OAuth without assuming a specific HTTP request object or web framework. Use it to graft OAuth client support onto your favorite HTTP library, or provide support onto your favourite web framework. If you're a maintainer of such a library, write a thin veneer on top of OAuthLib and get OAuth support for very little effort.
builddeps  :
    - python-blinker    # check
    - python-mock       # check
    - python-nose       # check
    - python-pyjwt      # check
    - python-setuptools
rundeps    :
    - python-cryptography
setup      : |
    # python-unittest2 is now provided by "python" package and python-unittest is retired
    sed -i "s/'unittest2', //" setup.py
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
